package com.SmartCampus.OperationHub.Enums;

public enum NotificationType {
    BOOKING_SUBMITTED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    TICKET_CREATED,
    TICKET_STATUS_CHANGED,
    TICKET_ASSIGNED,
    NEW_COMMENT,
    FACILITY_CREATED,
    FACILITY_UPDATED,
    FACILITY_STATUS_CHANGED,
    FACILITY_DELETED,
    USER_REGISTERED
}
